name: "LIBS"

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
    paths:
      - "libs/**"

jobs:
  compile_and_test:
    runs-on: ubuntu-latest

    steps:
      # https://apt.llvm.org/
      - name: Install clang-format v19
        run: |
          sudo apt remove -y clang clang-format
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          sudo apt install clang-format-19
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-19 100
          sudo update-alternatives --set clang-format /usr/bin/clang-format-19
      - uses: actions/checkout@v4
      - name: "Check format"
        run: make check_fmt
      - name: "Compile"
        run: make build
      - name: "Run tests"
        run: make test FAIL_FAST=true
