name: "Compile and test"

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
    paths:
      - "libs/**"

jobs:
  compile_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Check format"
        run: make check_fmt
      - name: "Compile"
        run: make build
      - name: "Run tests"
        run: make test FAIL_FAST=true
