name: "Compile CLI"

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
    paths:
      - "cli/**"

jobs:
  compile_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Check format"
        run: make cli_check_fmt
      - name: "Compile"
        run: make cli_build
